import type { Metadata } from "next";

import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased h-full w-full`}
      >
        <div className="w-full h-[20vh]  flex justify-between items-center px-32 absolute top-0 left-0 z-30" >
          <Link href="/"><div className="text-4xl font-semibold">Neuropulse</div></Link>
          <div className="flex gap-2">
            <Button variant={"ghost"}>Item 1</Button>
            <Button variant={"ghost"}>Item 2</Button>
            <Button variant={"ghost"}>Item 3</Button>
            <Button variant={"secondary"}>Item 4</Button>
            </div>
        </div>
        
        {children}
        
      </body>
    </html>
  );
}
